mysql-tripitaka:
  restart: always
  image: mysql
  volumes:
    - ./data/mysql/:/var/lib/mysql
    - ./conf/mysql/:/etc/mysql/conf.d
    - ./data/log/:/var/log/mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=lqtripitaka
    - MYSQL_ROOT_PASSWORD=root

nginx-tripitaka:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx/tripitaka_nginx.conf:/etc/nginx/conf.d/tripitaka_nginx.conf
  volumes_from:
    - web_tripitaka
  links:
    - web_tripitaka:web_tripitaka

web_tripitaka:
  restart: always
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/lqtripitaka
  links:
    - mysql-tripitaka:mysql_tripitaka
  command: uwsgi -s :8000 -w setting.wsgi -p 3



