# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TS', 'Translator'), ('AH', 'author')], default='TS', max_length=2)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('nameA', models.CharField(blank=True, default='', max_length=64)),
                ('nameB', models.CharField(blank=True, default='', max_length=64)),
                ('remark', models.CharField(max_length=128)),
            ],
        ),
    ]
