# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('cover', '封面'), ('prologue', '序言'), ('Preface', '前言'), ('catalog', '目录'), ('publish', '出版页'), ('blank', '空白页'), ('content', '内容')], default='content', max_length=8, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='pageresource',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_resources', to='core.Page', verbose_name='页'),
        ),
        migrations.AlterField(
            model_name='pageresource',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('inset', '插图')], default='text', max_length=8, verbose_name='类型'),
        ),
    ]
