# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='remark',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
