# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='end_page',
        ),
        migrations.AddField(
            model_name='roll',
            name='end_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='roll_end_page', to='core.Page', verbose_name='终止页'),
        ),
        migrations.RemoveField(
            model_name='roll',
            name='start_page',
        ),
        migrations.AddField(
            model_name='roll',
            name='start_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='roll_start_page', to='core.Page', verbose_name='起始页'),
        ),
    ]
