# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170718_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='lqsutra',
            name='roll_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='卷数'),
        ),
        migrations.AddField(
            model_name='lqsutra',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Translator', verbose_name='作译者'),
        ),
    ]
