# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170616_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sutra',
            name='end_page',
        ),
        migrations.AddField(
            model_name='sutra',
            name='end_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='sutra_end_page', to='core.Page', verbose_name='终止页'),
        ),
        migrations.RemoveField(
            model_name='sutra',
            name='start_page',
        ),
        migrations.AddField(
            model_name='sutra',
            name='start_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='sutra_start_page', to='core.Page', verbose_name='起始页'),
        ),
        migrations.RemoveField(
            model_name='volume',
            name='end_page',
        ),
        migrations.AddField(
            model_name='volume',
            name='end_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='volume_end_page', to='core.Page', verbose_name='终止页'),
        ),
        migrations.RemoveField(
            model_name='volume',
            name='start_page',
        ),
        migrations.AddField(
            model_name='volume',
            name='start_page',
            field=models.ManyToManyField(blank=True, null=True, related_name='volume_start_page', to='core.Page', verbose_name='起始页'),
        ),
    ]
