# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170617_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('sutra', 'code'), 'verbose_name': '页', 'verbose_name_plural': '页管理'},
        ),
        migrations.AlterModelOptions(
            name='roll',
            options={'ordering': ('sutra', 'code'), 'verbose_name': '卷', 'verbose_name_plural': '卷管理'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('code', 'type'), 'verbose_name': '藏经版本', 'verbose_name_plural': '藏经版本管理'},
        ),
        migrations.AlterModelOptions(
            name='sutra',
            options={'ordering': ('series', 'code'), 'verbose_name': '经', 'verbose_name_plural': '经管理'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ('series', 'code'), 'verbose_name': '册', 'verbose_name_plural': '册管理'},
        ),
        migrations.AlterField(
            model_name='pageresource',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('inset', '插图')], default='image', max_length=8, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='sutra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='core.Sutra', verbose_name='经'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sutras', to='core.Series', verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='core.Series', verbose_name='版本'),
        ),
    ]
