# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170614_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='版本名')),
                ('dynasty', models.CharField(max_length=64, verbose_name='朝代')),
                ('historic_site', models.CharField(max_length=64, verbose_name='刻经地点')),
                ('type', models.CharField(choices=[('SS', 'Series'), ('OP', 'Offprint')], default='SS', max_length=2, verbose_name='版本类型')),
                ('volume_count', models.IntegerField(verbose_name='册数')),
                ('sutra_count', models.IntegerField(verbose_name='经数')),
                ('publish_name', models.CharField(max_length=64, verbose_name='出版社')),
                ('publish_date', models.DateField(verbose_name='出版时间')),
                ('publish_edition', models.SmallIntegerField(verbose_name='版次')),
                ('publish_prints', models.SmallIntegerField(verbose_name='印次')),
                ('publish_ISBN', models.CharField(max_length=64, verbose_name='ISBN')),
                ('remark', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='translator',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='作译者名字'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='nameA',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='名字A'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='nameB',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='名字B'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='remark',
            field=models.TextField(verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='type',
            field=models.CharField(choices=[('TS', 'Translator'), ('AH', 'author')], default='TS', max_length=2, verbose_name='作者/译者'),
        ),
    ]
