# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170616_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='end_page',
        ),
        migrations.AddField(
            model_name='volume',
            name='end_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_end_page', to='core.Page', verbose_name='终止页'),
        ),
        migrations.RemoveField(
            model_name='volume',
            name='start_page',
        ),
        migrations.AddField(
            model_name='volume',
            name='start_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_start_page', to='core.Page', verbose_name='起始页'),
        ),
    ]
