# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170614_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='publish_date',
            field=models.DateField(auto_now=True, verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='series',
            name='publish_prints',
            field=models.SmallIntegerField(null=True, verbose_name='印次'),
        ),
    ]
