# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170722_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='core.Roll', verbose_name='卷'),
        ),
    ]
