# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pageresource_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='标准名')),
                ('type', models.CharField(choices=[('series', '标准版本名'), ('sutra', '标准经名'), ('dynasty', '标准朝代'), ('site', '标准地名'), ('trans', '标准作译者')], default='sutra', max_length=8, verbose_name='标准条目')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '标准名',
                'verbose_name_plural': '标准名管理',
            },
        ),
        migrations.CreateModel(
            name='NormNameMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('series', '标准版本名'), ('sutra', '标准经名'), ('dynasty', '标准朝代'), ('site', '标准地名'), ('trans', '标准作译者')], default='sutra', max_length=8, verbose_name='标准条目')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('norm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_list', to='core.NormName', verbose_name='标准名')),
            ],
            options={
                'verbose_name': '标准名关联',
                'verbose_name_plural': '标准名关联管理',
            },
        ),
        migrations.AlterField(
            model_name='pageresource',
            name='source',
            field=models.CharField(choices=[('cbeat', 'cbeta采集'), ('hand', '手工录入'), ('net', '网络采集')], default='hand', max_length=8, verbose_name='来源'),
        ),
    ]
