# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170616_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='end_page',
        ),
        migrations.AddField(
            model_name='roll',
            name='end_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_end_page', to='core.Page', verbose_name='终止页'),
        ),
        migrations.RemoveField(
            model_name='roll',
            name='start_page',
        ),
        migrations.AddField(
            model_name='roll',
            name='start_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_start_page', to='core.Page', verbose_name='起始页'),
        ),
        migrations.RemoveField(
            model_name='sutra',
            name='end_page',
        ),
        migrations.AddField(
            model_name='sutra',
            name='end_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sutra_end_page', to='core.Page', verbose_name='终止页'),
        ),
        migrations.RemoveField(
            model_name='sutra',
            name='start_page',
        ),
        migrations.AddField(
            model_name='sutra',
            name='start_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sutra_start_page', to='core.Page', verbose_name='起始页'),
        ),
    ]
