# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170614_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='版本名')),
            ],
        ),
        migrations.AlterField(
            model_name='series',
            name='publish_prints',
            field=models.SmallIntegerField(verbose_name='印次'),
        ),
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('SS', '藏经丛书'), ('OP', '单行本')], default='SS', max_length=2, verbose_name='版本类型'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='name',
            field=models.CharField(max_length=64, verbose_name='作译者名字'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='nameA',
            field=models.CharField(max_length=64, verbose_name='名字A'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='nameB',
            field=models.CharField(max_length=64, verbose_name='名字B'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='type',
            field=models.CharField(choices=[('TS', '译者'), ('AH', '作者')], default='TS', max_length=2, verbose_name='作者/译者'),
        ),
    ]
