# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170724_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lqsutra',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='龙泉编码'),
        ),
        migrations.AlterField(
            model_name='lqsutra',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='龙泉经名'),
        ),
        migrations.AlterField(
            model_name='normname',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='标准名'),
        ),
        migrations.AlterField(
            model_name='normnamemap',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='page',
            name='series',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='部'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sutra',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='经'),
        ),
        migrations.AlterField(
            model_name='page',
            name='volume',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='册'),
        ),
        migrations.AlterField(
            model_name='pageresource',
            name='source',
            field=models.CharField(choices=[('cbeat', 'cbeta采集'), ('hand', '手工录入'), ('net', '网络采集')], db_index=True, default='hand', max_length=8, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='pageresource',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('inset', '插图'), ('pdf', 'PDF')], db_index=True, default='image', max_length=8, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='type',
            field=models.CharField(choices=[('roll', '卷'), ('preface', '序'), ('all_preface', '总序'), ('origin_preface', '原序'), ('catalogue', '总目'), ('postscript', '跋'), ('corrigenda', '勘误表')], db_index=True, default='roll', max_length=16, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='type',
            field=models.CharField(choices=[('ST', '经'), ('RT', '律'), ('TT', '论')], db_index=True, default='ST', max_length=2, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='作译者名字'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
    ]
