# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170622_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normnamemap',
            options={'verbose_name': '标准名关联', 'verbose_name_plural': '名称对照管理'},
        ),
        migrations.AlterField(
            model_name='normname',
            name='type',
            field=models.CharField(choices=[('series', '标准版本名'), ('sutra', '标准经名'), ('dynasty', '标准朝代'), ('site', '标准地名'), ('trans', '标准作译者')], default='sutra', max_length=8, verbose_name='标准类型'),
        ),
        migrations.AlterField(
            model_name='normnamemap',
            name='name',
            field=models.CharField(max_length=64, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='normnamemap',
            name='norm_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_list', to='core.NormName', verbose_name='隶属标准名'),
        ),
        migrations.AlterField(
            model_name='normnamemap',
            name='type',
            field=models.CharField(choices=[('series', '标准版本名'), ('sutra', '标准经名'), ('dynasty', '标准朝代'), ('site', '标准地名'), ('trans', '标准作译者')], default='sutra', max_length=8, verbose_name='标准类型'),
        ),
    ]
