# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170725_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lqsutra',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='龙泉编码'),
        ),
        migrations.AlterField(
            model_name='lqsutra',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='龙泉经名'),
        ),
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='编号'),
        ),
    ]
