# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170809_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='作译者名字'),
        ),
    ]
