# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170628_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='type',
            field=models.CharField(choices=[('preface', 'preface'), ('roll', 'roll'), ('postscript', 'script')], default='roll', max_length=8, verbose_name='类型'),
        ),
    ]
