# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_roll_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='lqSutra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, unique=True, verbose_name='龙泉编码')),
                ('name', models.CharField(max_length=64, verbose_name='龙泉经名')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '龙泉经录',
                'verbose_name_plural': '龙泉收录管理',
            },
        ),
        migrations.AlterField(
            model_name='roll',
            name='type',
            field=models.CharField(choices=[('roll', '卷'), ('preface', '序'), ('all_preface', '总序'), ('origin_preface', '原序'), ('catalogue', '总目'), ('postscript', '跋'), ('corrigenda', '勘误表')], default='roll', max_length=16, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='sutra',
            name='lq_sutra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lq_sutra_list', to='core.lqSutra', verbose_name='龙泉收录'),
        ),
    ]
