# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170707_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sutra',
            name='lq_sutra',
        ),
        migrations.AddField(
            model_name='sutra',
            name='lqsutra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lqsutra_list', to='core.lqSutra', verbose_name='龙泉收录'),
        ),
    ]
