# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170710_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='页数'),
        ),
        migrations.AddField(
            model_name='series',
            name='roll_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='卷数'),
        ),
        migrations.AddField(
            model_name='series',
            name='word_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='字数'),
        ),
        migrations.AddField(
            model_name='sutra',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='页数'),
        ),
        migrations.AddField(
            model_name='sutra',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='volume',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='页数'),
        ),
        migrations.AddField(
            model_name='volume',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='资源'),
        ),
        migrations.AlterField(
            model_name='pageresource',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('inset', '插图'), ('pdf', 'PDF')], default='image', max_length=8, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='core.Series', verbose_name='版本'),
        ),
    ]
