# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170712_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutra',
            name='lqsutra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lqsutra_list', to='core.LQSutra', verbose_name='龙泉收录'),
        ),
    ]
