# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170713_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='next_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='下一页'),
        ),
        migrations.AlterField(
            model_name='page',
            name='pre_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一页'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='end_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='终止页'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='end_volume',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='终止册'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='start_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='起始页'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='start_volume',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='起始册'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='end_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='终止页'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='end_volume',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='终止册'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='lqsutra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lqsutra_list', to='core.LQSutra', verbose_name='龙泉收录'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='start_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='起始页'),
        ),
        migrations.AlterField(
            model_name='sutra',
            name='start_volume',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='起始册'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='end_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='终止页'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='start_page',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='起始页'),
        ),
    ]
